# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KIRSTIN HALL // DIGITAL COMPOSITOR
email: kirstin.hall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a versatile compositor with 11 years professional experience in film, television, broadcast and commercials.
  <br><br>
  Software: Nuke, Katana, Digital Fusion, After Effects, Silhouette and Roto, Photoshop, Illustrator, Shake, Mocha Pro and Maya
  <br><br>
  Specialties: Compositing, complicated scene reconstruction or retouching, digital paint, keying difficult screens, look development, stereo compositing/conversion, lighting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kirstinhall.com" # the base hostname & protocol for your site
# twitter_username: khallTweets
# github_username:  khall

# Build settings
markdown: kramdown



